console.log("primeira linha \n segunda linha")
console.log("O meu nome é 'Matheus'")
console.log('O meu nome é "Matheus"')
console.log(`a multiplicação de 5 por 3 é ${5*3}`)
console.log("teste" + " teste")